SELECT TOP (1000) [MusteriID]
      ,[SirketAdi]
      ,[MusteriAdi]
      ,[MusteriUnvani]
      ,[Adres]
      ,[Sehir]
      ,[Bolge]
      ,[PostaKodu]
      ,[Ulke]
      ,[Telefon]
      ,[Faks]
  FROM [Northwind].[dbo].[Musteriler]
