--CROSS APPLY 
SELECT 
C.CITY, D.DATE_,
ISNULL(
(SELECT SUM(TOTALPRICE) FROM ORDERS O 
JOIN ADDRESS A ON A.ID = O.ADDRESSID
WHERE A.CITYID = C.ID AND CONVERT(DATE,O.DATE_) = D.DATE_),0) TOPLAMCIRO
FROM CITIES C
CROSS APPLY (SELECT * FROM DATES) D
WHERE C.CITY = 'ARTVÝN'


--CROSS APPLY EX 1
SELECT 
C.CITY SEHIR, ORDERINFO_MAX.BRAND ENCOKSATILANMARKA, ORDERINFO_MAX.TOTALSALE,
ORDERINFO_MIN.BRAND, ORDERINFO_MIN.TOTALSALE
FROM CITIES C
CROSS APPLY (
	SELECT TOP 1
	I.BRAND, SUM(OD.LINETOTAL) TOTALSALE
	FROM ORDERS O 
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) ORDERINFO_MAX
CROSS APPLY
(
	SELECT TOP 1
	I.BRAND, SUM(OD.LINETOTAL) TOTALSALE
	FROM ORDERS O 
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) ORDERINFO_MIN


--CROSS APPLY EX 2, HER BIR KULLANICININ EN SON ALIÞVERÝÞ YAPTIGI TARIHI, SEHRI VE ADRESI GETIREN SORGUYU YAZINIZ
SELECT U1.ID, U1.NAMESURNAME ADSOYAD, ORDERINFO.*
FROM USERS U1 
CROSS APPLY
(
SELECT TOP 1 O.DATE_, A.ADDRESSTEXT, C.CITY, T.TOWN, D.DISTRICT,
I.ITEMNAME, O.TOTALPRICE
FROM ORDERS O 
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS	D ON D.ID = A.DISTRICTID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE U.ID = U1.ID
ORDER BY O.DATE_ DESC, OD.ID DESC
) ORDERINFO





