--HER BIR KULLANICININ SAHIP OLDUGU ADRES SAYISI
SELECT U.ID, U.NAMESURNAME, COUNT(A.ID) 
FROM USERS U 
INNER JOIN ADDRESS A ON A.USERID = U.ID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 1

	--SUBQUERY
	SELECT U.ID, U.NAMESURNAME,
	(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID)
	FROM USERS U 


--SEHRI ISTANBUL OLAN SATISLARI GETIRME
SELECT O.ID, O.DATE_, O.TOTALPRICE FROM ORDERS O 
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
WHERE C.CITY = 'ÝSTANBUL'

	--SUBQUERY
	SELECT  O.ID, O.DATE_, O.TOTALPRICE FROM ORDERS O 
	WHERE ADDRESSID IN
	(
		SELECT ID FROM ADDRESS 
			WHERE CITYID =
				(SELECT ID FROM CITIES WHERE CITY = 'ÝSTANBUL')
	)


--HER URUN ICIN TOPLAM SATIS ADEDI, TOPLAM SATIS CITOSU, EN DUSUK SATIS FIYATI
--EN YUKSEK SATIS FIYATI VE ORTALAMA SATIS FIYATINI GETIREN SORGUYU SUBQUERY ILE YAZINIZ
SET STATISTICS IO ON
SELECT I.ID, I.ITEMCODE, I.ITEMNAME, I.BRAND,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = I.ID),
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID = I.ID),
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID),
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID),
(SELECT ROUND(AVG(UNITPRICE),2) FROM ORDERDETAILS WHERE ITEMID = I.ID)
FROM ITEMS I
ORDER BY 5  --1 TANE SATILMAYAN URUN VAR, INNER JOIN'DE BU URUN GELMIYORDU


--HER MARKA ICIN TOPLAM URUN SAYISI, TOPLAM ANA KATEGORI SAYISI 
--VE TOPLAM ALT KATEGORI SAYISINI GETIREN SORGUYU SUBQUERY ILE YAZINIZ
 
SELECT DISTINCT BRAND MARKA,
(SELECT COUNT(DISTINCT CATEGORY1) FROM ITEMS WHERE BRAND = I.BRAND) KATEGORI_1,
(SELECT COUNT(DISTINCT CATEGORY2) FROM ITEMS WHERE BRAND = I.BRAND) KATEGORI_2,
(SELECT COUNT(*) FROM ITEMS WHERE BRAND = I.BRAND) URUN_SAYISI
FROM ITEMS I


--GIDA VE DETERJAN TEMIZLIK KATEGORILERININ HANGI SEHIRDE NE KADAR
--SATILDIGINI YAN YANA GETIREN SQL CUMLESINI SUBQUERY ILE YAZINIZ
SELECT C.CITY,
(
	SELECT SUM(OD.LINETOTAL) FROM ORDERS O 
	JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = 'GIDA' 
	AND A.CITYID = C.ID
) GIDA,
(
	SELECT SUM(OD.LINETOTAL) FROM ORDERS O 
	JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = 'DETERJAN TEMÝZLÝK' 
	AND A.CITYID = C.ID
) DETERJAN_TEMIZLIK
FROM CITIES C


--HER BIR SEHIR ICIN TOPLAM KAC ERKEK VE KADIN MUSTERI OLDUGUNU ERKEK VE KADIN SAYISI YAN YANA
--OLACAK SEKILDE GETIREN SORGUYU SUBQUERY ILE YAZINIZ
SELECT ID, CITY SEHIR,
(
	SELECT COUNT(DISTINCT USERID) FROM USERS U 
	JOIN ADDRESS A ON A.USERID = U.ID
	WHERE U.GENDER = 'E' AND A.CITYID = C.ID 
) ERKEKSAYISI,
(
	SELECT COUNT(DISTINCT USERID) FROM USERS U 
	JOIN ADDRESS A ON A.USERID = U.ID
	WHERE U.GENDER = 'K' AND A.CITYID = C.ID 
) KADINSAYISI
FROM CITIES C


--SEHIRLERIN AYLARA GORE SATISINI AYLAR YAN YANA OLACAK SEKILDE GETIRINIZ
SELECT C.CITY SEHIR,
(
	SELECT ROUND(SUM(O.TOTALPRICE),0) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 1 
) OCAK
--TUM AYLAR ICIN TEKRAR YAZILABILIR
FROM CITIES C


--BOLGELERIN AYLARA GORE SATISINI AYLAR YAN YANA OLACAK SEKILDE GETIRINIZ
SELECT BOLGE, SUM(OCAK) OCAK 
FROM
(
SELECT C.REGION BOLGE, C.CITY CITY,
(
	SELECT ROUND(SUM(O.TOTALPRICE),0) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 1 	
) OCAK
--TUM AYLAR ICIN TEKRAR YAZILABILIR
FROM CITIES C
) T
GROUP BY BOLGE
ORDER BY BOLGE

--HER BIR SEHIR ICIN EN COK ALISVERIS YAPILAN KATEGORI ILE EN AZ ALISVERIS YAPILAN 
--KATEGORILERI GETIREN SORGUYU YAZINIZ

SELECT C.CITY,
(
	SELECT TOP  1 I.CATEGORY2  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) DESC
) EN_COK_SATILAN_KATEGORI,
(
	SELECT TOP   1 SUM(OD.LINETOTAL)  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) DESC
) TOPLAM_TUTAR,
(
	SELECT TOP  1 I.CATEGORY2  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) ASC
) EN_AZ_SATILAN_KATEGORI,
(
	SELECT TOP   1 SUM(OD.LINETOTAL)  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) ASC
) TOPLAM_TUTAR

FROM CITIES C


--HER BIR SEHIR ICIN EN COK ALISVERIS YAPILAN MARKA ILE EN AZ ALISVERIS YAPILAN
--MARKALARI GETIREN SORGUYU YAZINIZ

SELECT C.CITY,
(
	SELECT TOP 1 I.BRAND  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY  I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
	
) EN_COK_SATILAN_MARKA,
(
	SELECT TOP 1 SUM(OD.LINETOTAL)  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY  I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) TOPLAM_TUTAR,
(
	SELECT TOP 1 I.BRAND  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY  I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC

) EN_AZ_SATILAN_MARKA,
(
	SELECT TOP 1 SUM(OD.LINETOTAL)  FROM ORDERS O 
	JOIN ORDERDETAILS OD  ON O.ID = OD.ORDERID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY  I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) TOPLAM_TUTAR

FROM CITIES C


--HER BIR MARKA ICIN EN COK VE EN AZ SATILAN KATEGORILERI GETIRINIZ

SELECT DISTINCT BRAND,
(
	SELECT TOP 1 I.CATEGORY1 FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) DESC

) EN_FAZLA_SATILAN_KATEGORI,
(
	SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) DESC

) TUTAR,
(
	SELECT TOP 1 I.CATEGORY1 FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) ASC

) EN_AZ_SATILAN_KATEGORI,
(
	SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) ASC

) TUTAR

FROM ITEMS I1


--HER BIR KATEGORI ICIN EN COK SATILAN MARKA VE EN AZ SATILAN MARKAYI YAN YANA YAZDIRINIZ
SELECT DISTINCT CATEGORY1,
(
	SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) EN_FAZLA_SATILAN_MARKA,
(
	SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
)TUTAR,
(
	SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) EN_AZ_SATILAN_MARKA,
(
	SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
)TUTAR
FROM ITEMS I1


--2'DEN FAZLA ADRESI OLAN KULLANICILARI SUBQUERY ILE GETIRINIZ

--JOIN METODU
SELECT U.ID,
U.NAMESURNAME, COUNT(A.ID)
FROM USERS U 
JOIN ADDRESS A ON A.USERID = U.ID
GROUP BY U.ID, U.NAMESURNAME
HAVING COUNT(A.ID) > 2
ORDER BY 3 DESC


	--SUBQUERY
	SELECT 
	U.NAMESURNAME KULLANICI,
	(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) ADRESSAYISI
	FROM USERS U
	WHERE (SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) > 2

	--DYNAMIC VIEW 
	SELECT * FROM
	(
		SELECT 
		U.NAMESURNAME KULLANICI,
		(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) ADRESSAYISI
		FROM USERS U
	) T
	WHERE ADRESSAYISI > 2


--AYNI SEHIRDE 2'DEN FAZLA ADRESI OLAN KULLANICILARI GETIRINIZ
SELECT 
U.ID , U.NAMESURNAME ADSOYAD, 
(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID),
(
	SELECT COUNT(ID) FROM ADDRESS WHERE USERID = U.ID 
	GROUP BY 
	CITYID  HAVING COUNT(ID) > 2
) AYNISEHIRADRESSAYISI

FROM USERS U
WHERE 
(
SELECT COUNT(ID) FROM ADDRESS WHERE USERID = U.ID 
GROUP BY 
CITYID  HAVING COUNT(ID) > 2
) IS NOT NULL


--HER BIR KULLANICININ EN SON ALISVERIS YAPTIGI TARIHI SEHRI VE ADRESI GETIREN SORGUYU YAZINIZ
SELECT U.ID, U.NAMESURNAME ADSOYAD,
(
	SELECT MAX(DATE_) FROM ORDERS O WHERE USERID = U.ID
) EN_SON_ALIVERIS_TARIHI,
(
	SELECT TOP 1 C.CITY FROM ORDERS O 
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	WHERE O.USERID = U.ID
	ORDER BY DATE_ DESC
) EN_SON_ALISVERIS_YAPILAN_SEHIR,
(
	SELECT TOP 1 A.ADDRESSTEXT FROM ORDERS O 
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	WHERE O.USERID = U.ID
	ORDER BY DATE_ DESC
) EN_SON_ALISVERIS_YAPILAN_ADRES,
(
	SELECT TOP 1 I.ITEMNAME FROM ORDERS O 
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE O.USERID = U.ID
	ORDER BY DATE_ DESC, OD.ID DESC
	
)EN_SON_ALINAN_URUN

FROM USERS U






