--ÞART BLOKLARI

	-- IF 
	--CANNOT BE USED IN SELECT STATEMENTS
	
	DECLARE @EXAMRESULT AS INT = 70
	DECLARE @STATUS_ AS VARCHAR(20)

	IF @EXAMRESULT > 60
		SET @STATUS_ = 'BAÞARILI'
	ELSE 
		SET @STATUS_ =  'BAÞARISIZ'

	SELECT @EXAMRESULT, @STATUS_
	--

	DECLARE @STATUS VARCHAR(20)
	DECLARE @POINT AS INT = 2
	
	IF @POINT = 1
		SET @STATUS = 'ÇOK KÖTÜ'
	IF @POINT = 2
		SET @STATUS = 'KÖTÜ'
	IF @POINT = 3
		SET @STATUS = 'NE ÝYÝ NE KÖTÜ'
	IF @POINT = 4
		SET @STATUS = 'ÝYÝ'
	IF @POINT = 5
		SET @STATUS = 'ÇOK ÝYÝ'

	SELECT @POINT, @STATUS
	

	--IIF
	--CAN BE USED IN SELECT STATEMENTS, WORKS ONLY FOR 2 ASSESMENT

	
	DECLARE @CUSTOMERGENDER AS VARCHAR = 'K'
	SELECT IIF(@CUSTOMERGENDER ='K', 'Kadýn', 'Erkek')
	

	--CASE WHEN

	DECLARE @AGE AS INT=70

	SELECT 
	CASE 
		WHEN @AGE < 35 THEN 'GENÇ'
		WHEN @AGE BETWEEN 35 AND 60 THEN 'ORTA'
		WHEN @AGE > 60 THEN 'YAÞLI'
	END AS AGEGROUP






