--DATETIME FUNCTIONS EXERCISES

	--LAB01
	--DOGUM GUNU BUGUN OLANLARI GETIRINIZ
	SELECT * FROM LAB01
	WHERE DATEPART(MONTH, BIRTHDATE) = DATEPART(MONTH, GETDATE()) 
	AND DATEPART(DAY,BIRTHDATE) = DATEPART(DAY,GETDATE())

	--LAB02
	--DOGUM GUNU 1 HAFTA SONRA OLAN MUSTERILERIN LISTESINI GETIRINIZ
	SELECT * FROM LAB02
	WHERE DATEPART(MONTH, BIRTHDATE) = DATEPART(MONTH, DATEADD(DAY,7,GETDATE())) 
	AND DATEPART(DAY,BIRTHDATE) = DATEPART(DAY,DATEADD(DAY,7,GETDATE()))

	--LAB03
	--DOGUM YILI TELEFON NUMARASINDA GECEN MUSTERILERI TESPIT EDECEK SQL SORGUSUNU YAZINIZ

	SELECT ID, NAME_, SURNAME, BIRTHDATE, DATEPART(YEAR,BIRTHDATE)  ,
	TELNR1, TELNR2
	FROM LAB03
	WHERE TELNR1 LIKE '%' + CONVERT(varchar,DATEPART(YEAR,BIRTHDATE)) + '%'

	--LAB04
	--BARCODEDATE VE ISLEMLER ICIN BASLAMA BITIS ZAMANI VAR
	--KESILEN HER FATURA ICIN MUSTERININ KASADA NE KADAR BEKLEDIGINI 
	--BULAN SQL SORGUSUNU YAZINIZ

	SELECT DISTINCT INVOICENO FATURANO, DATE_ ISLEMBASLAMAZAMANI, INVOICEDATE ISLEMBITISZAMANI,
	DATEDIFF(SECOND,DATE_,INVOICEDATE) BEKLEMEZAMANI
	FROM LAB04
	ORDER BY 4
	
	SELECT INVOICENO FATURANO, MIN(DATE_) ISLEMBASLAMAZAMANI, MIN(INVOICEDATE) ISLEMBITISZAMANI,
	DATEDIFF(SECOND,MIN(DATE_),MIN(INVOICEDATE)) BEKLEMEZAMANI
	FROM LAB04
	GROUP BY INVOICENO
	ORDER BY 4

	--LAB05
	--KASADA ORTALAMA BEKLEME SURESINI HER BIR SEHIR ICIN HESAPLAYINIZ
	SELECT 
	CITY, AVG(BEKLEMEZAMANI)
	FROM
	(
	SELECT DISTINCT INVOICENO FATURANO, CITY, DATE_ ISLEMBASLAMAZAMANI, INVOICEDATE ISLEMBITISZAMANI,
	DATEDIFF(SECOND,DATE_,INVOICEDATE) BEKLEMEZAMANI
	FROM LAB05
	) T
	GROUP BY CITY
	ORDER BY CITY

	--LAB06
	--BIR URUNUN ORTALAMA OKUTULMA SURESI
	SELECT CITY SEHIR, SUM(DURATION) TOPLAMBEKLEME, SUM(TOTALAMOUNT) TOPLAMOKUTULANURUN
	, ROUND(SUM(DURATION) / SUM(TOTALAMOUNT),2) ORTALAMABIRURUNOKUTMAPERFORMANSI
	FROM
	(
	SELECT INVOICENO, CITY, 
	MIN(BARCODEDATE) FIRSTBARDATE, 
	MAX(BARCODEDATE) LASTBARDATE, 
	DATEDIFF(SECOND, MIN(BARCODEDATE), 
	MAX(BARCODEDATE)) DURATION, 
	SUM(AMOUNT) TOTALAMOUNT, 
	COUNT(ITEMCODE) ITEMCOUNT
	FROM LAB06
	GROUP BY INVOICENO, CITY
	) T
	GROUP BY CITY
	ORDER BY CITY


	--LAB07
	--KUTUCUKLARA GUN AY YIL OLARAK YAZILAN DOGUM TARIHLERINI
	--VARCHAR TURUNDEKI BIRTHDATE VE DATE TURUNDEKI BIRTHDATE2 ALANINI GUNCELLEYINIZ
	SELECT 
	ISDATE(BIRTHDATE),
	* FROM LAB07

	UPDATE LAB07 SET BIRTHDATE = YEAR_ + '-' + MONTH_ + '-' + DAY_
	UPDATE LAB07 SET BIRTHDATE2 = BIRTHDATE WHERE ISDATE(BIRTHDATE) = 1
	/*
	Aktarilamayan verilere manuel olarak duzeltme yapilmasi gerekiyor.
	*/


	--LAB08
	--HANGI SAAT NE KADAR YORUM ATILMIS?
	SELECT DATEPART(HOUR, CreationDate), COUNT(Text)
	FROM LAB08
	GROUP BY DATEPART(HOUR, CreationDate)
	ORDER BY 1

	--LAB09
	--HAFTANIN HANGI GUNU NE KADAR YORUM ATILMIS
	SET LANGUAGE 'turkish'
	SELECT DATENAME(DW, CreationDate), COUNT(Text)
	FROM LAB09
	GROUP BY DATEPART(DW, CreationDate),  DATENAME(DW, CreationDate)
	ORDER BY  DATEPART(DW, CreationDate)
	/*
	Pazartesi	385619
	Salý		433316
	Çarþamba	442096
	Perþembe	435285
	Cuma		388335
	Cumartesi	203659
	Pazar		210803
	*/

	--VEHICLEPASS
	SELECT Z.ZONENAME BOLGE, V.PLATE PLAKA, VP.DATE_ TARIH
	FROM VEHICLEPASS VP
	JOIN ZONES Z ON Z.ID = VP.ZONEID
	JOIN VEHICLES V  ON  V.ID = VP.VEHICLEID
	WHERE DATE_ >= DATEADD(SECOND, -30, GETDATE())
	ORDER BY BOLGE




	









	







