--CONDITION BLOCKS EXERCISES

	--LAB01
	
	DECLARE @CITY AS VARCHAR(100) 
	DECLARE @MONTH AS INT = 1
	DECLARE @BEGDATE AS DATE 
	DECLARE @ENDDATE AS DATE 

	IF @CITY IS NULL
		SET @CITY = '%'
	IF @BEGDATE IS NULL AND @ENDDATE IS NULL
		BEGIN
		SET @BEGDATE = DATEFROMPARTS(2022,@MONTH,1)
		SET @ENDDATE = DATEADD(MONTH, 1, @BEGDATE)
		END

	SELECT DATEPART(MONTH, DATE_) MONTH_,
	CITY, SUM(TOTALPRICE) TOTALPRICE
	FROM SALES
	WHERE CITY LIKE @CITY
	AND DATE_ BETWEEN @BEGDATE AND @ENDDATE
	GROUP BY DATEPART(MONTH, DATE_), CITY



	--LAB02

	
	DECLARE @TOTALPRICE AS FLOAT
	DECLARE @AVGPRICE AS FLOAT

	SELECT @TOTALPRICE = SUM(TOTALPRICE)
	FROM SALES
	SET @AVGPRICE = @TOTALPRICE / 81

	SELECT CITY, ROUND(SUM(TOTALPRICE),0) TOTALPRICE,
	IIF(SUM(TOTALPRICE) > @AVGPRICE, 'Ortalamanýn Üstünde', 'Ortalamanýn Altýnda') STATUS
	FROM SALES
	GROUP BY CITY
	ORDER BY CITY

	SELECT CITY, ROUND(SUM(TOTALPRICE),0) TOTALPRICE,
	CASE 
		WHEN SUM(TOTALPRICE) > @AVGPRICE THEN 'ORTALAMANIN ÜSTÜNDE'
		ELSE 'ORTALAMANIN ALTINDA'
	END AS STATUS
	FROM SALES
	GROUP BY CITY
	ORDER BY CITY
	

	--LAB03
	SELECT 
	CASE 
		WHEN MONTH(DATE_) = 1 THEN '01.Ock'
		WHEN MONTH(DATE_) = 2 THEN '02.Þub'
		WHEN MONTH(DATE_) = 3 THEN '03.Mar'
		WHEN MONTH(DATE_) = 4 THEN '04.Nis'
		WHEN MONTH(DATE_) = 5 THEN '05.May'
		WHEN MONTH(DATE_) = 6 THEN '06.Haz'
		WHEN MONTH(DATE_) = 7 THEN '07.Tem'
		WHEN MONTH(DATE_) = 8 THEN '08.Agu'
		WHEN MONTH(DATE_) = 9 THEN '09.Eyl'
		WHEN MONTH(DATE_) = 10 THEN '10.Ekm'
		WHEN MONTH(DATE_) = 11 THEN '11.Kas'
		WHEN MONTH(DATE_) = 12 THEN '12.Ara'
	END AS MONTH_,
	SUM(TOTALPRICE)
	FROM SALES
	GROUP BY MONTH(DATE_)
	ORDER BY 1




