--LOOP EXERCISES 

	--LAB01
	
	DECLARE  @I AS INT=0
	WHILE @I < 1000
	BEGIN 
		DECLARE @DEVICEID AS INT
		DECLARE @LASTVALUE AS FLOAT 
		DECLARE @LASTDATE AS DATETIME
		DECLARE @CURRENTVALUE AS FLOAT
		DECLARE @DATE AS DATETIME
		DECLARE @RAND AS FLOAT
		DECLARE @RAND2 AS INT

		SET @DEVICEID = 1 + RAND() * 99

		SELECT @LASTVALUE = LASTVALUE, @LASTDATE = LASTDATE, @DEVICEID = ID
		FROM THERMOMETERS
		WHERE ID = @DEVICEID

		SET @RAND = 2 *( -0.5 + RAND())
		SET @CURRENTVALUE = @LASTVALUE + @RAND

		SET @RAND2 = 15 + RAND() * 45
		SET @DATE = DATEADD(SECOND, @RAND2, @LASTDATE)


		INSERT INTO THERMOVALUES(DEVICEID, VALUE_,DATE_)
		VALUES (@DEVICEID, @CURRENTVALUE, @DATE)

		UPDATE THERMOMETERS SET LASTDATE = @DATE, @LASTVALUE = @CURRENTVALUE 
		WHERE ID = @DEVICEID

	SET @I = @I + 1
	END
	
	SELECT * FROM THERMOVALUES
	ORDER BY DATE_ DESC
	

	-- LAB02
	
	DECLARE @NAME AS VARCHAR(100)
	DECLARE @SURNAME AS VARCHAR(100)
	DECLARE @NAMESURNAME AS VARCHAR(100)
	DECLARE @GENDER AS VARCHAR(100)
	DECLARE @BIRTHDATE AS DATE
	DECLARE @CITY VARCHAR(100)
	DECLARE @RAND AS INT

	SELECT TOP 1 @NAME = NAME_, @GENDER=GENDER FROM NAMES ORDER BY NEWID()
	SELECT TOP 1 @SURNAME = SURNAME FROM SURNAMES ORDER BY NEWID()
	
	SET @NAMESURNAME = @NAME + ' ' + @SURNAME 
	SELECT TOP 1 @CITY = CITY FROM CITIES ORDER BY NEWID()
	
	SET @RAND = 365 * 50 
	SET @BIRTHDATE = DATEADD(DAY, @RAND, '1950-01-01')
	 
	INSERT INTO CUSTOMERS (NAME_,SURNAME,NAMESURNAME,GENDER,BIRTHDATE,CITY) 
	VALUES (@NAME, @SURNAME,@NAMESURNAME, @GENDER, @BIRTHDATE, @CITY)
	GO 10000
	

	--LAB03
	DECLARE @USERID AS INT 
	DECLARE @ADDRESSID AS INT
	DECLARE @DATE_ AS DATETIME
	DECLARE @TOTALPRICE AS FLOAT
	DECLARE @STATUS AS INT = 1
	DECLARE @RAND AS INT

	DECLARE @ORDERID AS INT
	DECLARE @ITEMID AS INT
	DECLARE @AMOUNT AS INT 
	DECLARE @UNITPRICE AS FLOAT
	DECLARE @LINETOTAL AS FLOAT

	SELECT TOP 1 @USERID = ID FROM USERS ORDER BY NEWID()
	SELECT TOP 1 @ADDRESSID = ID FROM ADDRESS WHERE USERID = @USERID ORDER BY NEWID()
	SET @RAND = RAND() * 365
	SET @DATE_ = DATEADD(DAY,@RAND, '2022-01-01')
	SET @RAND = RAND () * 24 * 60 * 60 
	SET @DATE_ = DATEADD(SECOND, @RAND, @DATE_)

	INSERT INTO ORDERS(USERID, ADDRESSID, DATE_, STATUS_, TOTALPRICE)
	VALUES (@USERID, @ADDRESSID, @DATE_, @STATUS, @TOTALPRICE)
	
	SET  @ORDERID = @@IDENTITY
	SELECT TOP 1 @ITEMID = ID, @UNITPRICE = UNITPRICE FROM ITEMS ORDER BY NEWID()
	SET @RAND = 1 + RAND() * 9 
	SET @AMOUNT = @RAND 
	SET @LINETOTAL= @AMOUNT * @UNITPRICE

	INSERT INTO ORDERDETAILS(ORDERID, ITEMID, AMOUNT, UNITPRICE, LINETOTAL)
	VALUES (@ORDERID, @ITEMID, @AMOUNT, @UNITPRICE, @LINETOTAL)

	UPDATE ORDERS SET TOTALPRICE = (SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ORDERID = ORDERS.ID)
	WHERE ID = @ORDERID

	GO 1000

	SELECT * FROM ORDERS
	SELECT * FROM ORDERDETAILS





