--VARIABLE EXERCISES 

	--LAB 01
	
	DECLARE @NAME AS VARCHAR(100)
	DECLARE @SURNAME AS VARCHAR(100)
	DECLARE @NAMESURNAME AS VARCHAR(100)

	SET @NAME = 'HAKAN'
	SET @SURNAME = 'YAVAÞ'
	--SET @NAMESURNAME = @NAME + ' ' + @SURNAME
	SET @NAMESURNAME = CONCAT(@NAME, ' ', @SURNAME)

	SELECT @NAMESURNAME
	PRINT @NAMESURNAME
	

	--LAB 02
	
	DECLARE @DT AS DATETIME 
	DECLARE @D AS DATE
	DECLARE @T AS TIME 
	DECLARE @DSTR AS VARCHAR(30)
	DECLARE @TSTR AS VARCHAR(30)

	SET @DT = '2022-06-24 12:56:21'
	SET @D = @DT
	SET @T = @DT
	SET @DSTR = CONVERT(VARCHAR, @DT, 104)
	SET @TSTR = CONVERT(VARCHAR, @DT, 108)

	SELECT @DT DT, @D D, @T T, @DSTR DSTR, @TSTR TSTR
	

	--LAB03

	
	DECLARE @MONTH AS INT
	DECLARE @DAY AS INT
	DECLARE @NAME_ AS VARCHAR(100)
	DECLARE @SURNAME_ AS VARCHAR(100)
	DECLARE @BIRTHDATE AS DATE
	DECLARE @AGE AS INT
	DECLARE @NAMESURNAME_ AS VARCHAR(100)
	DECLARE @MSG AS VARCHAR(1000)

	SET @MONTH = DATEPART(MONTH,GETDATE())
	SET @DAY = DATEPART(DAY,GETDATE())

	SELECT TOP 1 @NAME_= NAME_, @SURNAME_ = SURNAME, @BIRTHDATE = BIRTHDATE FROM LAB03
	WHERE DATEPART(MONTH, BIRTHDATE) = @MONTH
	AND  DATEPART(DAY, BIRTHDATE) = @DAY
	ORDER BY NEWID()

	SET @NAMESURNAME_ = CONCAT(@NAME_, ' ', @SURNAME_)
	SET @AGE = DATEDIFF(YEAR,@BIRTHDATE, GETDATE())

	SET @MSG = 'Sayýn ' + @NAMESURNAME_ + ',' + CONVERT(VARCHAR, @AGE) +'. Yaþýnýzý kutlarýz!'

	PRINT @MSG
	

	--LAB04
	
	
	SELECT * FROM NAMES 
	SELECT * FROM SURNAMES
	SELECT * FROM CITIES
	

	
	DECLARE @NAME AS VARCHAR(100)
	DECLARE @SURNAME AS VARCHAR(100)
	DECLARE @NAMESURNAME AS VARCHAR(100)
	DECLARE @GENDER AS VARCHAR(1)
	DECLARE @CITY AS VARCHAR(100)
	DECLARE @BIRTHDATE AS DATE
	DECLARE @RAND AS INT

	SET @RAND = 1 + RAND()*609
	SELECT TOP 1 @NAME = NAME_, @GENDER = GENDER FROM NAMES WHERE ID = @RAND

	SET @RAND = 1 + RAND()*797
	SELECT TOP 1 @SURNAME = SURNAME FROM SURNAMES WHERE ID = @RAND

	SET @RAND = RAND()*50*365
	SET @BIRTHDATE = DATEADD(DAY,@RAND, '1950-01-01')

	SET @NAMESURNAME = CONCAT(@NAME, ' ', @SURNAME)
	SELECT @NAME NAME_, @GENDER GENDER, @SURNAME SURNAME, @NAMESURNAME NAMESURNAME, @BIRTHDATE BIRTHDATE
	


	--LAB05
	
	SELECT * FROM USERS
	SELECT * FROM ITEMS
	SELECT * FROM SALES
	

	
	DECLARE @USERID AS INT
	DECLARE @ITEMID AS INT
	DECLARE @DATE AS DATETIME
	DECLARE @AMOUNT AS INT
	DECLARE @UNITPRICE AS FLOAT
	DECLARE @LINETOTAL AS FLOAT
	DECLARE @RAND AS INT

	SELECT TOP 1 @USERID = ID FROM USERS ORDER BY NEWID()
	SELECT TOP 1 @ITEMID = ID, @UNITPRICE = UNITPRICE FROM ITEMS ORDER BY NEWID()
	SET @RAND = RAND()*365
	SET @DATE = DATEADD(DAY,@RAND,'2022-01-01')
	SET @RAND = 28800 + RAND() * 43200
	SET @DATE = DATEADD(SECOND, @RAND, @DATE)
	SET @AMOUNT = 1 +  RAND() * 19
	SET @LINETOTAL = @AMOUNT * @UNITPRICE
	SELECT @USERID USERID, @ITEMID ITEMID, @DATE DATE_, @AMOUNT AMOUNT, @UNITPRICE UNITPRICE, @LINETOTAL LINETOTAL

	INSERT INTO SALES(CUSTOMERID,ITEMID,DATE_,AMOUNT,UNITPRICE,LINETOTAL)
	VALUES (@USERID,@ITEMID,@DATE,@AMOUNT,@UNITPRICE,@LINETOTAL)

	SELECT U.NAMESURNAME, I.ITEMNAME, S.* FROM SALES S
	JOIN USERS U ON U.ID = S.CUSTOMERID
	JOIN ITEMS I ON I.ID = S.ITEMID
	

	--LAB07

	DECLARE @BEGDATE AS DATE = '2022-04-01'
	DECLARE @ENDDATE AS DATE = '2022-05-01'
	DECLARE @CITY AS VARCHAR(100) = 'ANKARA,ÝZMÝR,ÝSTANBUL,ADANA,KONYA'

	SELECT CITY, SUM(TOTALPRICE) FROM LAB07 
	WHERE DATE_ BETWEEN @BEGDATE AND @ENDDATE
	AND CITY IN (SELECT * FROM string_split(@CITY,','))
	GROUP BY CITY
	





















	









